# Generated by Django 3.1.7 on 2021-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210525_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='number',
            field=models.IntegerField(),
        ),
    ]
